global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'publisher'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'publisher:8082' ]
  - job_name: 'worker'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'worker:8081' ]
  - job_name: 'proxy'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'proxy:8083' ]
  - job_name: 'eurekaserver'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'eurekaserver:8085' ]
  - job_name: 'configserver'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'configserver:8084' ]
  - job_name: 'gatewayserver'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'gatewayserver:8080' ]